### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/libuvc#1]
currently `libuvc` does not work on windows. An issue that discusses the problem can be found here: https://github.com/ktossell/libuvc/issues/12

Below are the steps required to close this issue:
1.  Add isochronous  transfer support to the windows backend of libusb: https://github.com/libusb/libusb/issues/46
2. Test/fix libuvc functions (device enumeration, streaming and control) on windows.
3. Successfully stream mjpeg images from uvc compatible camera at 1080p 30fps.
4. Add documentation for building and use of libuvc and libusb on windows.
5. Add documentation for building and use of [pyuvc](https://github.com/pupil-labs/pyuvc) on windows.

libuvc should support windows 8.2 and later.

**Comment by willpatera** [comment]
Closed with PR #2
