### ISSUE TITLE
import issue w/ uvc

### ISSUE THREAD

**Issue by matiarj** [pupil-labs/libuvc#16]
mj@mjUbuntu:~/Documents/libuvc/build$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uvc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/libuvc.so: undefined symbol: libusb_handle_events_completed

i keep running into this problem any help?

**Comment by mkassner** [comment]
Hi,

we just fixed this please pull recent master.
