### ISSUE TITLE
unable to receive uncompressed image frames directly from camera

### ISSUE THREAD

**Issue by camcse** [pupil-labs/libuvc#20]
Hi - Is it possible to receive uncompressed (YUYV) image frames directly from cameras without having to decode?

I am passing UVC_FRAME_FORMAT_YUYV  in **uvc_get_stream_ctrl_format_size** like this
status = uvc_get_stream_ctrl_format_size ( devh, &ctrl, **UVC_FRAME_FORMAT_YUYV**, 640, 480, 30)

In the received uvc_frame, frame_format(uvc_frame_format) is UVC_FRAME_FORMAT_YUYV which is correct but the frame dump shows it is still an mjpeg frame. Please tell me what am I missing here.

OS - Windows 10, Cameras - USB cameras in Pupil ET addon for Oculus DK2
Camera Device Configuration file attached
[camera_configuration.txt](https://github.com/pupil-labs/libuvc/files/1449070/camera_configuration.txt)

**Comment by mkassner** [comment]
This should work when using libuvc without pyuvc. We did not alter the code here in regards to the origin.
