### ISSUE TITLE
Using usbdk on Windows

### ISSUE THREAD

**Issue by PeterPeterPan** [pupil-labs/libuvc#43]
Hi all,
Dose this fork support Usbdk?
I mean, when I modify the func uvc_init() in init.c (Reference from the libusb wiki)

```
libusb_init(&ctx->usb_ctx);
libusb_set_option(ctx->usb_ctx, LIBUSB_OPTION_USE_USBDK);
```
Then operate UsbDk_1.0.22_x64.msi
Finally run the code.

I got the log:

>  "uvc: device has a status interrupt endpoint, but unable to read from it"

-
The reason I want to use Usbdk is,
when I use the WinUSB, I can set command but can't open stream,
when I use the libusbK, I can set command and show stream but some device unplugging will cause my Windows blue-screen.

Any idea? thanks.

**Comment by papr** [comment]
Hey @PeterPeterPan 
We do not officially support `Usbdk`, i.e. we won't be able to help you with this part.

Was your unplugging issue solved with #44 ?

**Comment by PeterPeterPan** [comment]
Hi @papr 
thank for your reply!
I haven't found a solution for the issue unplugging cause blue-screen.
#44 just for video streaming hang or crash as uvc_stop_streaming( ) called.

**Comment by papr** [comment]
@PeterPeterPan Which camera are you using. I am not aware of such an issue with any of the official Pupil Labs cameras.

**Comment by PeterPeterPan** [comment]
@papr 
I have tried three cameras
1.  BisonCam, NB Pro
2. AVerVision M15W
3. Live Streamer CAM 313

After uvc_open( ), then pull out the device.
Only 2. will cause blue-screen, so I really don't know it's cause by libusb, libusbK or some specific devices.

**Comment by PeterPeterPan** [comment]
@papr 
I remove some process designed by myself, the blue-screen didn't appear anymore. 😨 
(I used uvc_open() two times, but the first time didn't close, maybe that's the reason cause MULTIPLE_IRP_COMPLETE_REQUESTS).

But why only camera 2. cause blue-screen and how to use usbdk? Still unknow.

**Comment by mcuee** [comment]
Please give libusb-1.0.26 a try, either with libusbk or WinUSB.

Latest build of https://github.com/pupil-labs/libuvc git head with libusb-1.0.26 (dynamic link) and pthreads-w32-2-9-1-release, using VS2019 (both 32bit and 64bit). 
[pupil_labs_libuvc.zip](https://github.com/libuvc/libuvc/files/8646865/pupil_labs_libuvc.zip)

**Comment by PeterPeterPan** [comment]
Thanks for the solutions you provided!
Although I don't currently have a project using libuvc.
The original problem was also due to the wrong process I designed.

Close this issue.
