### ISSUE TITLE
Win32 compiled libuvc for grabbing frames from PupilLab cameras

### ISSUE THREAD

**Issue by ghost** [pupil-labs/libuvc#45]
Hello everyone,
hope you are fine. 
I am trying to grab frames from some PupilLab cameras. 
Everything works fine using libuvc if this library is compiled for x64 architecture. On the other hand, when I compile libuvc targeting Win32, my grabbing frames homemade application crashes here: https://github.com/libusb/libusb/blob/master/libusb/io.c#L1694 with the following error message: `Exception thrown at 0x78D0982B (uvc.dll) in PupilLab32Bits.exe: 0xC0000094: Integer division by zero.`.
Has anyone tried to use Win32 compiled libuvc to grab frames from PupilLab cameras successfully? 
Thank you in advance!

**Comment by mcuee** [comment]
You may want to give libusb-1.0.26 a try to see if it helps.

Latest build of https://github.com/pupil-labs/libuvc git head with libusb-1.0.26 (dynamic link) and pthreads-w32-2-9-1-release, using VS2019 (both 32bit and 64bit). [pupil_labs_libuvc.zip](https://github.com/libuvc/libuvc/files/8646865/pupil_labs_libuvc.zip)
